# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0821d156556f0199cc24ec7e206246f"
name = "EyePop-AI-Bulk-Lister"
handle = "eyepop-ai-bulk-lister"
application_url = "https://eyepop-ai-bulk-lister-eye-pop-s-team.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://eyepop-ai-bulk-lister-eye-pop-s-team.vercel.app/auth/callback",
  "https://eyepop-ai-bulk-lister-eye-pop-s-team.vercel.app/auth/shopify/callback",
  "https://eyepop-ai-bulk-lister-eye-pop-s-team.vercel.app/api/auth/callback"
]

[pos]
embedded = false
