# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0821d156556f0199cc24ec7e206246f"
name = "eyepop-connector"
handle = "eyepop-connector"
application_url = "https://between-kelly-appearing-roberts.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://between-kelly-appearing-roberts.trycloudflare.com/auth/callback",
  "https://between-kelly-appearing-roberts.trycloudflare.com/auth/shopify/callback",
  "https://between-kelly-appearing-roberts.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
